# Generated by Django 5.2.16 on 2026-08-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('paid', "To'lov qilindi"), ('cancelled', 'Bekor qilindi')], db_index=True, default='pending', max_length=12),
        ),
    ]
