# Generated by Django 5.2.16 on 2026-08-04 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Raqam +998XXXXXXXXX ko'rinishida bo'lishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='Telefon'),
        ),
    ]
