# Generated by Django 5.2.16 on 2026-08-17 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Raqam +998XXXXXXXXX ko'rinishida bo'lishi kerak.", regex='^\\+998\\d{9}$')])),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Telegram kirish kodi',
                'verbose_name_plural': 'Telegram kirish kodlari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
