# Generated by Django 5.2.16 on 2026-08-04 07:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Boshlang'ich narx")),
                ('current_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Joriy narx')),
                ('min_increment', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))], verbose_name='Minimal qadam')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Boshlanmagan'), ('live', 'Jonli'), ('ended', 'Tugagan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='pending', max_length=10)),
                ('bids_count', models.PositiveIntegerField(default=0, editable=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='catalog.product')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auksion',
                'verbose_name_plural': 'Auksionlar',
                'ordering': ('end_at',),
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
                'ordering': ('-amount', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'end_at'], name='auctions_au_status_f43bfc_idx'),
        ),
        migrations.AddConstraint(
            model_name='auction',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='auction_ends_after_start'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-amount'], name='auctions_bi_auction_5888cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('auction', 'amount'), name='unique_amount_per_auction'),
        ),
    ]
