# Generated by Django 5.2.16 on 2026-08-25 09:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=25, verbose_name='Karta raqami')),
                ('holder_name', models.CharField(max_length=100, verbose_name='Karta egasi')),
                ('bank', models.CharField(blank=True, max_length=60, verbose_name='Bank')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name="Qo'shimcha izoh")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "To'lov kartasi",
                'verbose_name_plural': "To'lov kartalari",
                'ordering': ('-is_active', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Balans')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balans',
                'verbose_name_plural': 'Balanslar',
                'ordering': ('-amount',),
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('sale', 'Sotuvdan tushum'), ('withdrawal', 'Pul yechish'), ('adjustment', 'Admin tuzatishi')], default='sale', max_length=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Balansga o'tgan")),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.balance')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
            ],
            options={
                'verbose_name': 'Balans harakati',
                'verbose_name_plural': 'Balans harakatlari',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['balance', '-created_at'], name='payments_ba_balance_62311c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Summa')),
                ('status', models.CharField(choices=[('awaiting_receipt', 'Chek kutilmoqda'), ('pending', 'Tekshirilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], db_index=True, default='awaiting_receipt', max_length=20)),
                ('receipt_file_id', models.CharField(blank=True, max_length=200)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('receipt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('channel_message_id', models.BigIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=300, verbose_name='Rad etish sababi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentcard')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx')],
            },
        ),
    ]
