# Generated by Django 5.2.16 on 2026-08-04 07:48

import apps.common.translation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name_uz', models.CharField(max_length=80)),
                ('name_ru', models.CharField(blank=True, max_length=80)),
                ('name_en', models.CharField(blank=True, max_length=80)),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='Emoji yoki ikonka nomi')),
            ],
            options={
                'verbose_name': 'Hunar turi',
                'verbose_name_plural': 'Hunar turlari',
                'ordering': ('name_uz',),
            },
            bases=(apps.common.translation.TranslatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('shop_name_uz', models.CharField(max_length=100, verbose_name="Do'kon nomi")),
                ('shop_name_ru', models.CharField(blank=True, max_length=100)),
                ('shop_name_en', models.CharField(blank=True, max_length=100)),
                ('about_uz', models.TextField(blank=True, max_length=1500, verbose_name='Hunarmand haqida')),
                ('about_ru', models.TextField(blank=True, max_length=1500)),
                ('about_en', models.TextField(blank=True, max_length=1500)),
                ('region', models.CharField(blank=True, max_length=60, verbose_name='Viloyat')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='artisans/banners/%Y/%m/')),
                ('products_count', models.PositiveIntegerField(default=0, editable=False)),
                ('posts_count', models.PositiveIntegerField(default=0, editable=False)),
                ('sold_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL)),
                ('crafts', models.ManyToManyField(blank=True, related_name='artisans', to='artisans.craft')),
            ],
            options={
                'verbose_name': 'Hunarmand profili',
                'verbose_name_plural': 'Hunarmand profillari',
                'ordering': ('-created_at',),
            },
            bases=(apps.common.translation.TranslatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArtisanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(max_length=100, verbose_name="Do'kon nomi")),
                ('description', models.TextField(max_length=1500, verbose_name='Nima ishlab chiqarasiz')),
                ('region', models.CharField(blank=True, max_length=60)),
                ('document', models.FileField(blank=True, null=True, upload_to='applications/%Y/%m/', verbose_name='Hujjat')),
                ('status', models.CharField(choices=[('pending', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], db_index=True, default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_applications', to=settings.AUTH_USER_MODEL)),
                ('craft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='artisans.craft')),
            ],
            options={
                'verbose_name': 'Hunarmand arizasi',
                'verbose_name_plural': 'Hunarmand arizalari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caption', models.TextField(blank=True, max_length=2200, verbose_name='Matn')),
                ('likes_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='artisans.artisanprofile')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
