# Generated by Django 5.2.16 on 2026-08-04 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product',
            field=models.ForeignKey(blank=True, help_text="Post shu mahsulot haqida bo'lsa — bog'lang", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artisans.post'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='artisans.post'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='artisanprofile',
            index=models.Index(fields=['is_active', '-created_at'], name='artisans_ar_is_acti_0d8641_idx'),
        ),
        migrations.AddConstraint(
            model_name='artisanapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='one_pending_application_per_user'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['artisan', 'is_published', '-created_at'], name='artisans_po_artisan_64449f_idx'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='one_like_per_user_post'),
        ),
    ]
