# Generated by Django 5.2.16 on 2026-08-04 07:48

import apps.common.translation
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ('order', 'name_uz'),
            },
            bases=(apps.common.translation.TranslatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title_uz', models.CharField(max_length=140, verbose_name='Nomi')),
                ('title_ru', models.CharField(blank=True, max_length=140)),
                ('title_en', models.CharField(blank=True, max_length=140)),
                ('description_uz', models.TextField(blank=True, max_length=4000, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, max_length=4000)),
                ('description_en', models.TextField(blank=True, max_length=4000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Narx (so'm)")),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Zaxira')),
                ('sale_type', models.CharField(choices=[('fixed', 'Belgilangan narx'), ('auction', 'Auksion')], db_index=True, default='fixed', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Sotuvda'), ('sold', 'Sotilgan'), ('archived', 'Arxiv')], db_index=True, default='draft', max_length=10)),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='artisans.artisanprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ('-created_at',),
            },
            bases=(apps.common.translation.TranslatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text="Ko'rish qobiliyati cheklangan foydalanuvchilar uchun rasm tavsifi", max_length=200, verbose_name='Alt matn')),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ('-is_main', 'order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'sale_type', '-created_at'], name='catalog_pro_status_e09ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='catalog_pro_categor_da0f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['artisan', 'status'], name='catalog_pro_artisan_d12129_idx'),
        ),
    ]
