# Generated by Django 5.2.16 on 2026-08-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('application_approved', 'Ariza tasdiqlandi'), ('application_rejected', 'Ariza rad etildi'), ('new_comment', 'Yangi izoh'), ('order_placed', 'Buyurtma qabul qilindi'), ('new_order', 'Yangi buyurtma')], max_length=30),
        ),
    ]
