# Generated by Django 5.2.16 on 2026-08-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('application_approved', 'Ariza tasdiqlandi'), ('application_rejected', 'Ariza rad etildi'), ('new_comment', 'Yangi izoh'), ('order_placed', 'Buyurtma qabul qilindi'), ('new_order', 'Yangi buyurtma'), ('payment_approved', "To'lov tasdiqlandi"), ('payment_rejected', "To'lov rad etildi"), ('sale_paid', 'Mahsulot sotildi')], max_length=30),
        ),
    ]
